replicaCount: 2

image:
  gateway:
    repository: 188451452903.dkr.ecr.us-east-1.amazonaws.com/enkryptai-prod/gateway
    tag: "ec1a9d9"
    pullPolicy: IfNotPresent
  sync:
    repository: 188451452903.dkr.ecr.us-east-1.amazonaws.com/enkryptai-prod/gateway-sync
    tag: "ec1a9d9"
    pullPolicy: IfNotPresent
  fluentBit:
    repository: fluent/fluent-bit
    tag: "3.2.1"
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: "gateway-kong"

service:
  type: ClusterIP
  ports:
    http:
      port: 80
      targetPort: 8000
    https:
      port: 443
      targetPort: 8443
    admin:
      port: 8001
      targetPort: 8001
    adminGui:
      port: 8002
      targetPort: 8002
    fluentBitMetrics:
      port: 2020
      targetPort: 2020
    fluentBitAdmin:
      port: 5043
      targetPort: 5043

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
  hosts:
    - host: api.dev.enkryptai.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gateway-kong-tls
      hosts:
        - api.dev.enkryptai.com

resources:
  gateway:
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "0.5"
      memory: "1.5Gi"
  sync:
    limits:
      cpu: "0.5"
      memory: "256Mi"
    requests:
      cpu: "0.1"
      memory: "64Mi"
  fluentBit:
    limits:
      cpu: "0.5"
      memory: "256Gi"
    requests:
      cpu: "0.1"
      memory: "64Mi"

livenessProbe:
  enabled: true
  exec:
    command:
      - kong
      - health
  failureThreshold: 10
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

externalSecrets:
  enabled: true
  secretStoreRefName: enkryptai-clustersecret-store
  repoName: enkryptai/gateway

secrets:
  enabled: false
  KONG_DATABASE: postgres
  KONG_LOG_LEVEL: info
  KONG_MEM_CACHE_SIZE: 128m
  KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE: 50k
  KONG_NGINX_HTTP_KEEPALIVE_REQUESTS: 100000
  KONG_PG_DATABASE: kong
  KONG_PG_HOST: supabase-cluster
  KONG_PG_PASSWORD: kong-password
  KONG_PG_PORT: 5432
  KONG_PG_SSL:
  KONG_PG_SSL_REQUIRED: off
  KONG_PG_SSL_VERIFY: off
  KONG_PG_SSL_VERSION: any
  KONG_PG_USER: kong-user
  KONG_PROXY_ACCESS_LOG: off
  KONG_PROXY_LISTEN: 0.0.0.0:8000
  KONG_SSL_PROTOCOLS: TLSv1.1 TLSv1.2 TLSv1
  KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS: 100000
  DECK_APP_DASHBOARD_DOMAIN: fronte
  DECK_APP_DASHBOARD_DOMAIN_URL: http://frontend:30
  DECK_APP_DASHBOARD_PORT: 3000
  DECK_APP_DASHBOARD_SCHEME: http
  DECK_ELASTIC_HOST: enkryptai-opensearch-cluster
  DECK_ENKRYPT_ENVIRONMENT: loc
  DECK_FLUENT_BIT_HOST: 0.0.0.0
  DECK_GUARDRAILS_HOST: guardrails
  DECK_GUARDRAILS_PORT:
  DECK_GUARDRAILS_SCHEME: http
  DECK_INITIAL_SAMPLE_MODEL_PASSWORD: password
  DECK_INTERNAL_KONG_ADMIN_EMAIL: admin@enkrypt.com
  DECK_INTERNAL_KONG_ADMIN_PASSWORD: deck-admin-password
  DECK_INTERNAL_KONG_ADMIN_USERNAME: deck-kong-username
  DECK_KEYDB_HOST: key
  DECK_KONG_ADDR: http://0.0.0.0:8001
  DECK_KONG_LOGS_PLUGIN_ELASTIC_BASIC_AUTH: elastic-basic-auth
  DECK_LEADERBOARD_AUTH: leaderboard
  DECK_LEADERBOARD_CORS_ORIGIN: "*"
  DECK_LEADERBOARD_DETAILS_PASSWORD: leaderboard
  DECK_LEADERBOARD_HOST: leaderboard
  DECK_LEADERBOARD_PORT: leaderboard
  DECK_LEADERBOARD_PUBLIC_CONSUMER_API_KEY: leaderboard
  DECK_LEADERBOARD_PUBLIC_CONSUMER_EMAIL: leaderboard
  DECK_LEADERBOARD_SCHEME: http
  DECK_NEXT_JS_BASIC_AUTH:  js-basic-auth
  DECK_OPENFGA_AUTHORIZATION_MODEL_ID: openfga-model-id
  DECK_OPENFGA_STORE_ID: openfga-store-id
  DECK_OPENFGA_URL: http://openfga:8080
  DECK_RED_TEAMING_HOST: redteam-proxy
  DECK_RED_TEAMING_PORT: 9091
  DECK_RED_TEAMING_SCHEME: http
  DECK_RED_TEAMING_URL: http://redteam-proxy:9091
  DECK_SAMPLE_MODEL_REAL_APIKEY: sample-api-key
  DECK_VERCEL_PROTECTION_AUTH: xxxx
  KONG_ADMIN_LISTEN: 0.0.0.0:8001
  KONG_DATABASE: postgres
  KONG_LOG_LEVEL: error
  KONG_MEM_CACHE_SIZE: 128m
  KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE: 50k
  KONG_NGINX_HTTP_KEEPALIVE_REQUESTS: 100000
  KONG_PG_DATABASE: kong
  KONG_PG_HOST: supabase-cluster
  KONG_PG_PASSWORD: kong-pg-password
  KONG_PG_PORT: 5432
  KONG_PG_SSL:
  KONG_PG_SSL_REQUIRED: off
  KONG_PG_SSL_VERIFY: off
  KONG_PG_SSL_VERSION: any
  KONG_PG_USER: kong
  KONG_PROXY_ACCESS_LOG: off
  KONG_PROXY_LISTEN: 0.0.0.0:8000
  KONG_SSL_PROTOCOLS: TLSv1.1 TLSv1.2 TLSv1
  KONG_TRACING_INSTRUMENTATIONS: all
  KONG_TRACING_SAMPLING_RATE: 0.03
  KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS: 100000
configMaps:
  kongConfig:
    enabled: true
    name: gateway-kong-temp-config
  fluentBit:
    enabled: true
    name: fluent-bit-config

nodeSelector: {}

tolerations: []

affinity: {}
secrets:

fluentBit:
  env:
    - name: ELASTIC_HOST
      valueFrom:
        secretKeyRef:
          name: "gateway-env-secret"
          key: "DECK_ELASTIC_HOST"
    - name: ELASTIC_PORT
      value: "9200"
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: "enkryptai-opensearch-admin-password"
          key: "username"
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "enkryptai-opensearch-admin-password"
          key: "password"
