apiVersion: v2
name: cert-manager
description: cert manager from jetstack
version: 1.0.0
appVersion: "1.18.2"
dependencies:
  - name: cert-manager
    version: 1.18.2
    alias: cert-manager
    repository: "https://charts.jetstack.io"
