apiVersion: v2
name: sensors
description: A Helm chart for Kubernetes
type: application
version: "1.0.0"
appVersion: "1.0.0"
dependencies:
  - name: argocd-events
    version: 1.0.0
    alias: argocd-events
    repository: "file://./charts/argocd-events"
    condition: argocd-events.enabled
