apiVersion: v2
name: enkryptai-stack
description: Full-stack deployment of EnkryptAI services including guardrails, red teaming, AI gateway, and authentication
type: application
version: 1.1.20
appVersion: "1.1.20"
dependencies:
  - name: openfga
    version: 0.2.26
    alias: openfga
    repository: "https://openfga.github.io/helm-charts"
