apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: redteam-run-sensor
  namespace: argo-events
  annotations:
    "helm.sh/hook-weight": "10"
    "helm.sh/hook": post-install, post-upgrade
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  dependencies:
  - eventName: redteam
    eventSourceName: redteam-run
    name: redteam-run
  eventBusName: redteam-eventbus
  template:
    serviceAccountName: argo-events-sa
  triggers:
  - template:
      argoWorkflow:
        operation: submit
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dataKey: body
            dependencyName: redteam-run
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: redteam-run-job-
              namespace: redteam-jobs
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: dedicated
                        operator: In
                        values:
                        - redteaming
              arguments:
                parameters:
                - name: event-data
                  value: '{{"{{.Input.body}}"}}'
              entrypoint: process-order
              {{- with .Values.global.imagePullSecrets }}
              imagePullSecrets:
              {{ toYaml . | nindent 14 }}
              {{- end }}
              templates:
              - container:
                  command:
                  - python
                  - -m
                  - sentry.redteam.runner
                  envFrom:
                  - secretRef:
                      name: redteam-proxy-env-secret
                  - configMapRef:
                      name: redteam-proxy-env-cm
                  image: {{ .Values.sensor.jobImage }}:{{ .Values.sensor.jobversion}}
                  workingDir: /app
                  {{- if $.Values.sensor.env }}
                  env:
                    {{- toYaml $.Values.sensor.env | nindent 20 }}
                  {{- end }}
                inputs:
                  parameters:
                  - name: event-data
                name: process-order
              tolerations:
              - effect: NoSchedule
                key: app
                operator: Equal
                value: redteaming
      name: argo-workflow-trigger
