{{- if .Values.global.externalsecret }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.aws.ClusterSecretStoreName }}
  annotations:
    "helm.sh/hook-weight": "5"
    "helm.sh/hook": post-install,post-upgrade
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
{{- end }}
