apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
  labels:
    name: argo-events
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo
  labels:
    name: argo
---
apiVersion: v1
kind: Namespace
metadata:
  name: redteam-jobs
