apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_URL: {{ .Values.configMap.NEXT_PUBLIC_URL | quote }}
