{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: frontend-env-secret
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
