{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: frontend-env-secret
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{- if ne $key "enabled" }}
  {{ $key }}: {{ $val | default "" | toString | quote }}
  {{- end }}
  {{- end }}
{{- end }}
