---
# Admin User
apiVersion: opensearch.opster.io/v1
kind: OpensearchUser
metadata:
  name: admin
  annotations:
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook": post-install,post-upgrade
spec:
  passwordFrom:
    name: opensearch-cred
    key: password
  backendRoles:
    - admin
  opensearchCluster:
    name: enkryptai-opensearch

---
# Dashboard User
apiVersion: opensearch.opster.io/v1
kind: OpensearchUser
metadata:
  name: dashboarduser
  annotations:
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook": post-install,post-upgrade
spec:
  passwordFrom:
    name: opensearch-cred
    key: password
  opensearchCluster:
    name: enkryptai-opensearch

---
# Kong Logs Plugin User
apiVersion: opensearch.opster.io/v1
kind: OpensearchUser
metadata:
  name: kong-logs-plugin
  annotations:
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook": post-install,post-upgrade
spec:
  passwordFrom:
    name: opensearch-cred
    key: password
  backendRoles:
    - readall
  opensearchCluster:
    name: enkryptai-opensearch

---
# Kibana Read Only User
apiVersion: opensearch.opster.io/v1
kind: OpensearchUser
metadata:
  name: kibana-read-only
  annotations:
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook": post-install,post-upgrade
spec:
  passwordFrom:
    name: opensearch-cred
    key: password
  backendRoles:
    - readall
  opensearchCluster:
    name: enkryptai-opensearch
