{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-cred
  annotations:
    "helm.sh/hook-weight": "2"
    "helm.sh/hook": post-install, post-upgrade
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.opensearch }}
  {{- if ne $key "enabled" }}
  {{ $key }}: {{ $val | default "" | toString | quote }}
  {{- end }}
  {{- end }}
{{- end }}
