# ALERTING
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: alerting-read-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/opendistro/alerting/alerts/get
    - cluster:admin/opendistro/alerting/destination/get
    - cluster:admin/opendistro/alerting/monitor/get
    - cluster:admin/opendistro/alerting/monitor/search
  indexPermissions: []
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: alerting-ack-alerts
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/opendistro/alerting/alerts/*
  indexPermissions: []
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: alerting-full-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster_monitor
    - cluster:admin/opendistro/alerting/*
  indexPermissions:
    - indexPatterns:
        - '*'
      allowedActions:
        - indices_monitor
        - indices:admin/aliases/get
        - indices:admin/mappings/get
---
# ANOMALY DETECTION
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: anomaly-read-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/opendistro/ad/detector/info
    - cluster:admin/opendistro/ad/detector/search
    - cluster:admin/opendistro/ad/detectors/get
    - cluster:admin/opendistro/ad/result/search
    - cluster:admin/opendistro/ad/tasks/search
    - cluster:admin/opendistro/ad/detector/validate
    - cluster:admin/opendistro/ad/result/topAnomalies
  indexPermissions: []
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: anomaly-full-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster_monitor
    - cluster:admin/opendistro/ad/*
  indexPermissions:
    - indexPatterns:
        - '*'
      allowedActions:
        - indices_monitor
        - indices:admin/aliases/get
        - indices:admin/mappings/get
---
# NOTEBOOKS
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: notebooks-read-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/opendistro/notebooks/list
    - cluster:admin/opendistro/notebooks/get
  indexPermissions: []
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: notebooks-full-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/opendistro/notebooks/create
    - cluster:admin/opendistro/notebooks/update
    - cluster:admin/opendistro/notebooks/delete
    - cluster:admin/opendistro/notebooks/get
    - cluster:admin/opendistro/notebooks/list
  indexPermissions: []
---
# OBSERVABILITY
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: observability-read-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/opensearch/observability/get
  indexPermissions: []
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: observability-full-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/opensearch/observability/create
    - cluster:admin/opensearch/observability/update
    - cluster:admin/opensearch/observability/delete
    - cluster:admin/opensearch/observability/get
  indexPermissions: []
---
# REPORTS
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: reports-read-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/opendistro/reports/definition/get
    - cluster:admin/opendistro/reports/definition/list
    - cluster:admin/opendistro/reports/instance/list
    - cluster:admin/opendistro/reports/instance/get
    - cluster:admin/opendistro/reports/menu/download
  indexPermissions: []
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: reports-full-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/opendistro/reports/definition/create
    - cluster:admin/opendistro/reports/definition/update
    - cluster:admin/opendistro/reports/definition/on_demand
    - cluster:admin/opendistro/reports/definition/delete
    - cluster:admin/opendistro/reports/definition/get
    - cluster:admin/opendistro/reports/definition/list
    - cluster:admin/opendistro/reports/instance/list
    - cluster:admin/opendistro/reports/instance/get
    - cluster:admin/opendistro/reports/menu/download
  indexPermissions: []
---
# ASYNC SEARCH
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: asynchronous-search-full-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/opendistro/asynchronous_search/*
  indexPermissions:
    - indexPatterns:
        - '*'
      allowedActions:
        - indices:data/read/search*
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: asynchronous-search-read-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/opendistro/asynchronous_search/get
  indexPermissions: []
---
# INDEX MANAGEMENT
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: index-management-full-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/opendistro/ism/*
    - cluster:admin/opendistro/rollup/*
    - cluster:admin/opendistro/transform/*
  indexPermissions:
    - indexPatterns:
        - '*'
      allowedActions:
        - indices:admin/opensearch/ism/*
---
# CROSS CLUSTER REPLICATION
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: cross-cluster-replication-leader-full-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  indexPermissions:
    - indexPatterns:
        - '*'
      allowedActions:
        - indices:admin/plugins/replication/index/setup/validate
        - indices:data/read/plugins/replication/changes
        - indices:data/read/plugins/replication/file_chunk
  clusterPermissions: []
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: cross-cluster-replication-follower-full-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  clusterPermissions:
    - cluster:admin/plugins/replication/autofollow/update
  indexPermissions:
    - indexPatterns:
        - '*'
      allowedActions:
        - indices:admin/plugins/replication/index/setup/validate
        - indices:data/write/plugins/replication/changes
        - indices:admin/plugins/replication/index/start
        - indices:admin/plugins/replication/index/pause
        - indices:admin/plugins/replication/index/resume
        - indices:admin/plugins/replication/index/stop
        - indices:admin/plugins/replication/index/update
        - indices:admin/plugins/replication/index/status_check
---
# ------------------------------
# Tenants (from tenants.yml)
# ------------------------------
apiVersion: opensearch.opster.io/v1
kind: OpensearchTenant
metadata:
  name: global
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchTenant
metadata:
  name: admin
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchTenant
metadata:
  name: kibanaserver
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
---
# ------------------------------
# Role Mappings (from roles_mapping.yml)
# ------------------------------
apiVersion: opensearch.opster.io/v1
kind: OpensearchUserRoleBinding
metadata:
  name: all-access
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  roles:
    - all_access
  backendRoles:
    - admin
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchUserRoleBinding
metadata:
  name: own-index
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  roles:
    - own_index
  users:
    - "*"
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchUserRoleBinding
metadata:
  name: readall
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  roles:
    - readall
  backendRoles:
    - readall
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchUserRoleBinding
metadata:
  name: manage-snapshots
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  roles:
    - manage_snapshots
  backendRoles:
    - snapshotrestore
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchUserRoleBinding
metadata:
  name: dashboard-server
  annotations:
    "helm.sh/hook-weight": "7"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
  roles:
    - dashboard_server
  users:
    - dashboarduser
