apiVersion: v1
kind: Secret
metadata:
  name: opensearch-securityconfig
type: Opaque
stringData:
  action_groups.yml: |-
    _meta:
      type: "actiongroups"
      config_version: 2

  internal_users.yml: |-
    _meta:
      type: "internalusers"
      config_version: 2

    admin:
      hash: "{{ .Values.opensearch.users.admin.hash }}"
      reserved: true
      backend_roles:
        - "admin"
      description: "admin user"

    dashboarduser:
      hash: "{{ .Values.opensearch.users.dashboarduser.hash }}"
      reserved: true
      description: "Dashboards user"

    kong_logs_plugin:
      hash: "{{ .Values.opensearch.users.kong_logs_plugin.hash }}"
      reserved: true
      backend_roles:
        - "readall"
      description: "Kong plugin readall"

    kibana_read_only:
      hash: "{{ .Values.opensearch.users.kibana_read_only.hash }}"
      reserved: true
      backend_roles:
        - "readall"
      description: "Kibana read only"

  config.yml: |-
    _meta:
      type: "config"
      config_version: "2"
    config:
      dynamic:
        http:
          anonymous_auth_enabled: false
        authc:
          basic_internal_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: "4"
            http_authenticator:
              type: basic
              challenge: true
            authentication_backend:
              type: intern
