global: 
  platform: aws
  image: 
    registry: 188451452903.dkr.ecr.us-east-1.amazonaws.com

ingresscontroller:
  repository: onprem/ingress-controller
  tag: v1.13.3
webhook:
  repository: onprem/cert-manager-webhook
  tag: v1.19.1




