{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.secretName }}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRefName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: HF_TOKEN
{{- end }}
