{
 "title": "enkryptai-stack",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=~\"$namespace\"},label_app_kubernetes_io_name)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=~\"$namespace\", label_app_kubernetes_io_name=~\"$app\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\", app=~\"$app\", pod=~\"$pod\"} |= ``"
    }
   ]
  },
  {
   "title": "cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"$namespace\",\n    container!=\"POD\"\n  }[5m])\n  * on (namespace, pod)\n  group_left(label_app_kubernetes_io_name)\n  kube_pod_labels{\n    namespace=\"$namespace\",\n    label_app_kubernetes_io_name=~\"$app\"\n  }\n)\n",
     "legendFormat": "{{`{{ label_app_kubernetes_io_name}}`}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "total_container",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{`{{ container }}`}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pod Availability",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_status_ready{\n    namespace=\"$namespace\"\n  }\n  * on (pod)\n  group_left\n  kube_pod_labels{\n    namespace=\"$namespace\",\n    label_app_kubernetes_io_name=~\"$app\"\n  }\n)\n/\ncount(\n  kube_pod_container_status_ready{\n    namespace=\"$namespace\"\n  }\n  * on (pod)\n  group_left\n  kube_pod_labels{\n    namespace=\"$namespace\",\n    label_app_kubernetes_io_name=~\"$app\"\n  }\n)\n",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    kube_pod_container_status_restarts_total{\n      namespace=\"$namespace\"\n    }[30m]\n  )\n  * on (namespace, pod)\n  group_left\n  kube_pod_labels{\n    namespace=\"$namespace\",\n    label_app_kubernetes_io_name=~\"$app\"\n  }\n)\n",
     "legendFormat": "{{`{{ pod}}`}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU throttling ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_cfs_throttled_periods_total{\n    namespace=~\"$namespace\",\n    container!=\"POD\"\n  }[10m])\n  * on (namespace, pod)\n  group_left\n  kube_pod_labels{\n    namespace=\"$namespace\",\n    label_app_kubernetes_io_name=~\"$app\"\n  }\n)\n/\nsum by (pod) (\n  rate(container_cpu_cfs_periods_total{\n    namespace=\"$namespace\",\n    container!=\"POD\"\n  }[10m])\n  * on (namespace, pod)\n  group_left\n  kube_pod_labels{\n    namespace=\"$namespace\",\n    label_app_kubernetes_io_name=~\"$app\"\n  }\n)\n",
     "legendFormat": "{{`{{ label_app_kubernetes_io_name}}`}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory limit",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits{\n    namespace=\"$namespace\",\n    pod=~\"$pod\",\n    resource=\"memory\"\n  }\n)  / 1024 / 1024 /1024 \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu limit",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits{\n    namespace=\"$namespace\",\n    pod=~\"$pod\",\n    resource=\"cpu\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UP Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 27 },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_status_ready{\n    namespace=\"$namespace\"\n  }\n  * on (namespace, pod)\n  group_left\n  kube_pod_labels{\n    namespace=\"$namespace\",\n    label_app_kubernetes_io_name=~\"$app\"\n  }\n)\n/\ncount(\n  kube_pod_container_status_ready{\n    namespace=\"$namespace\"\n  }\n  * on (namespace, pod)\n  group_left\n  kube_pod_labels{\n    namespace=\"$namespace\",\n    label_app_kubernetes_io_name=~\"$app\"\n  }\n)\n",
     "legendFormat": "{{`{{ pod}}`}}"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}