{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.secretName }}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRefName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: LITELLM_MASTER_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DATABASE_URL
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: OPENAI_API_KEY
{{- end }}
