{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: litellm-gateway-env-secret
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{- if and (ne $key "enabled") (kindIs "string" $val) }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
