{{- if .Release.IsInstall }}
apiVersion: batch/v1
kind: Job
metadata:
  name: openfga-sync
  annotations:
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-openfga
          image: {{.Values.global.registry}}/{{.Values.busybox.repository}}:{{.Values.busybox.tag}}
          command: ["sh", "-c", "until wget -q --spider http://openfga:8080/healthz; do echo 'Waiting for OpenFGA...'; sleep 2; done"]
      containers:
        - name: openfga-sync
          image: {{.Values.global.registry}}/{{.Values.openfgaSyncJob.repository}}:{{.Values.openfgaSyncJob.tag}}
          env:
            - name: FGA_API_URL
              value: "http://openfga:8080"
            - name: FGA_MODEL_ID
              value: "latest"
{{- end }}
