apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.databaseSecretName }} 
  annotations:  
    "helm.sh/hook-weight": "2"
    "helm.sh/hook": post-install, post-upgrade
spec:
  refreshInterval: "15m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: enkryptai-clustersecret-store
  target: 
    name: onprem 
  data:
    - secretKey: GOTRUE_ADDITIONAL_REDIRECT_URLS
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_ADDITIONAL_REDIRECT_URLS
    - secretKey: SERVER_HEADERS_TIMEOUT
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: SERVER_HEADERS_TIMEOUT
    - secretKey: SERVER_KEEP_ALIVE_TIMEOUT
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: SERVER_KEEP_ALIVE_TIMEOUT
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: AWS_ACCESS_KEY_ID
    - secretKey: MINIO_LOG_LEVEL
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: MINIO_LOG_LEVEL
    - secretKey: S3_PROTOCOL_ALLOWS_SERVICE_KEY_AS_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: S3_PROTOCOL_ALLOWS_SERVICE_KEY_AS_SECRET
    - secretKey: S3_PROTOCOL_ACCESS_KEY_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: S3_PROTOCOL_ACCESS_KEY_SECRET
    - secretKey: S3_PROTOCOL_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: S3_PROTOCOL_ACCESS_KEY_ID
    - secretKey: GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE
    - secretKey: GOTRUE_MAILER_URLPATHS_RECOVERY
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_MAILER_URLPATHS_RECOVERY
    - secretKey: GOTRUE_MAILER_URLPATHS_CONFIRMATION
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_MAILER_URLPATHS_CONFIRMATION
    - secretKey: GOTRUE_MAILER_URLPATHS_INVITE
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_MAILER_URLPATHS_INVITE
    - secretKey: GOTRUE_SMS_AUTOCONFIRM
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_SMS_AUTOCONFIRM
    - secretKey: GOTRUE_JWT_EXP
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_JWT_EXP
    - secretKey: GOTRUE_JWT_AUD
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_JWT_AUD
    - secretKey: GOTRUE_JWT_ADMIN_ROLES
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_JWT_ADMIN_ROLES
    - secretKey: GOTRUE_JWT_DEFAULT_GROUP_NAME
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_JWT_DEFAULT_GROUP_NAME
    - secretKey: GOTRUE_DISABLE_SIGNUP
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_DISABLE_SIGNUP
    - secretKey: GOTRUE_URI_ALLOW_LIST
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_URI_ALLOW_LIST
    - secretKey: GOTRUE_API_PORT
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_API_PORT
    - secretKey: GOTRUE_API_HOST
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_API_HOST
    - secretKey: DASHBOARD_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: DASHBOARD_PASSWORD
    - secretKey: DASHBOARD_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: DASHBOARD_USERNAME
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: MINIO_ROOT_PASSWORD
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: MINIO_ROOT_USER
    - secretKey: DB_PASSWORD_ENC
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: DB_PASSWORD_ENC
    - secretKey: NEXT_ANALYTICS_BACKEND_PROVIDER
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: NEXT_ANALYTICS_BACKEND_PROVIDER
    - secretKey: STUDIO_PORT
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: STUDIO_PORT
    - secretKey: SUPABASE_PUBLIC_URL
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: SUPABASE_PUBLIC_URL
    - secretKey: NEXT_PUBLIC_ENABLE_LOGS
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: NEXT_PUBLIC_ENABLE_LOGS
    - secretKey: SUPABASE_URL
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: SUPABASE_URL
    - secretKey: STUDIO_PG_META_URL
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: STUDIO_PG_META_URL
    - secretKey: STUDIO_DEFAULT_PROJECT
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: STUDIO_DEFAULT_PROJECT
    - secretKey: STUDIO_DEFAULT_ORGANIZATION
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: STUDIO_DEFAULT_ORGANIZATION
    - secretKey: DEFAULT_ORGANIZATION_NAME
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: DEFAULT_ORGANIZATION_NAME
    - secretKey: TENANT_ID
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: TENANT_ID
    - secretKey: GOTRUE_MAILER_TEMPLATES_CONFIRMATION
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_MAILER_TEMPLATES_CONFIRMATION
    - secretKey: GOTRUE_MAILER_TEMPLATES_MAGIC_LINK
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_MAILER_TEMPLATES_MAGIC_LINK
    - secretKey: DB_SSL
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: DB_SSL
    - secretKey: DB_DRIVER
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: DB_DRIVER
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: DB_NAME
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: DB_USERNAME
    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: DB_PORT
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: DB_HOST
    - secretKey: GOTRUE_SMTP_SENDER_NAME
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_SMTP_SENDER_NAME
    - secretKey: GOTRUE_SMTP_PORT
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_SMTP_PORT
    - secretKey: GOTRUE_SMTP_HOST
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_SMTP_HOST
    - secretKey: GOTRUE_SMTP_ADMIN_EMAIL
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_SMTP_ADMIN_EMAIL
    - secretKey: GOTRUE_MAILER_AUTOCONFIRM
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_MAILER_AUTOCONFIRM
    - secretKey: GOTRUE_MAILER_EXTERNAL_HOSTS
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_MAILER_EXTERNAL_HOSTS
    - secretKey: GOTRUE_EXTERNAL_EMAIL_ENABLED
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_EXTERNAL_EMAIL_ENABLED
    - secretKey: GOTRUE_EXTERNAL_GOOGLE_ENABLED
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_EXTERNAL_GOOGLE_ENABLED
    - secretKey: GOTRUE_SITE_URL
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_SITE_URL
    - secretKey: API_EXTERNAL_URL
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: API_EXTERNAL_URL
    - secretKey: S3accessKey
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: S3accessKey
    - secretKey: S3keyId
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: S3keyId
    - secretKey: dashboardpassword
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: dashboardpassword
    - secretKey: dashboardusername
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: dashboardusername
    - secretKey: smtppassword
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: smtppassword
    - secretKey: smtpusername
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: smtpusername
    - secretKey: dbdatabase
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: dbdatabase
    - secretKey: dbpassword
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: dbpassword
    - secretKey: dbusername
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: dbusername
    - secretKey: secretjwt
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: secretjwt
    - secretKey: serviceKey
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: serviceKey
    - secretKey: GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_URI
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_URI
    - secretKey: GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_ENABLED
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_ENABLED
    - secretKey: anonKey
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: anonKey
    - secretKey: GOTRUE_DB_DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_DB_DATABASE_URL 
    - secretKey: GOTRUE_MAILER_OTP_LENGTH
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_MAILER_OTP_LENGTH
    - secretKey: GOTRUE_MAILER_SUBJECTS_MAGIC_LINK
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_MAILER_SUBJECTS_MAGIC_LINK
    - secretKey: GOTRUE_EXTERNAL_REDIRECT_URLS
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property: GOTRUE_EXTERNAL_REDIRECT_URLS
    - secretKey:  GOTRUE_REFRESH_TOKEN_EXPIRY
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property:  GOTRUE_REFRESH_TOKEN_EXPIRY
    - secretKey: GOTRUE_SESSION_IDLE_TIMEOUT
      remoteRef:
        key: {{ .Values.externalSecret.databaseSecretRepoName }}
        property:  GOTRUE_SESSION_IDLE_TIMEOUT

