#   AWS_ACCESS_KEY_ID: your-access-key
#   AWS_SECRET_ACCESS_KEY: your-secret-key
#   AWS_DEFAULT_REGION: ap-south-1
apiVersion: batch/v1
kind: Job
metadata:
  name: create-s3-folders
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
        - name: s3-folder-init
          image: amazon/aws-cli:2.17.18
          env:
            - name: BUCKET_NAME
              value: {{ .Values.global.bucketName }}
          envFrom:
            - secretRef:
                name: {{ .Values.global.bucketSecret }} 
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "🔍 Checking and creating folders in S3 bucket: $BUCKET_NAME ..."
              FOLDERS=(
                "redteam/"
                "red_teaming/"
                "playground/"
                "datasets/"
                "dataset_red_teaming/"
                "leaderboard/"
                "code-of-conduct/"
                "redteam_reports/"
              )

              for folder in "${FOLDERS[@]}"; do
                echo "➡️ Checking if $folder exists..."
                if aws s3api list-objects-v2 --bucket "$BUCKET_NAME" --prefix "$folder" --max-items 1 | grep -q '"Key"'; then
                  echo " $folder already exists. Skipping."
                else
                  echo " Creating $folder..."
                  aws s3api put-object --bucket "$BUCKET_NAME" --key "$folder"
                fi
              done
              echo "✅ Folders created successfully."

