apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elastic-env-secret
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRefName }}
    kind: ClusterSecretStore
  target:
    name: elastic-env-secret
  data:
    - secretKey: ELASTIC_HOST
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: ELASTIC_HOST
    - secretKey: ELASTIC_PORT
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: ELASTIC_PORT
    - secretKey: ELASTIC_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: ELASTIC_USERNAME
    - secretKey: ELASTIC_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: ELASTIC_PASSWORD
    - secretKey: STAKATER_FLUENT_BIT_CONFIG_CONFIGMAP
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: STAKATER_FLUENT_BIT_CONFIG_CONFIGMAP
    - secretKey: STAKATER_GATEWAY_MIGRATION_ENV_SECRET_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: STAKATER_GATEWAY_MIGRATION_ENV_SECRET_SECRET

