{{- if .Values.externalSecret.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-env-secret
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRefName }}
    kind: ClusterSecretStore
  target:
    name: gateway-env-secret
  data:
    - secretKey: KONG_TRACING_INSTRUMENTATIONS
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_TRACING_INSTRUMENTATIONS
    - secretKey: KONG_TRACING_SAMPLING_RATE
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_TRACING_SAMPLING_RATE
    - secretKey: DECK_OPENFGA_URL
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_OPENFGA_URL
    - secretKey: DECK_OPENFGA_STORE_ID
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_OPENFGA_STORE_ID
    - secretKey: DECK_OPENFGA_AUTHORIZATION_MODEL_ID
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_OPENFGA_AUTHORIZATION_MODEL_ID
    - secretKey: DECK_APP_DASHBOARD_DOMAIN
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_APP_DASHBOARD_DOMAIN
    - secretKey: DECK_APP_DASHBOARD_DOMAIN_URL
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_APP_DASHBOARD_DOMAIN_URL
    - secretKey: DECK_APP_DASHBOARD_PORT
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_APP_DASHBOARD_PORT
    - secretKey: DECK_APP_DASHBOARD_SCHEME
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_APP_DASHBOARD_SCHEME
    - secretKey: DECK_ELASTIC_HOST
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_ELASTIC_HOST
    - secretKey: DECK_ENKRYPT_ENVIRONMENT
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_ENKRYPT_ENVIRONMENT
    - secretKey: DECK_FLUENT_BIT_HOST
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_FLUENT_BIT_HOST
    - secretKey: DECK_GUARDRAILS_HOST
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_GUARDRAILS_HOST
    - secretKey: DECK_GUARDRAILS_PORT
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_GUARDRAILS_PORT
    - secretKey: DECK_GUARDRAILS_SCHEME
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_GUARDRAILS_SCHEME
    - secretKey: DECK_INTERNAL_KONG_ADMIN_EMAIL
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_INTERNAL_KONG_ADMIN_EMAIL
    - secretKey: DECK_INTERNAL_KONG_ADMIN_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_INTERNAL_KONG_ADMIN_USERNAME
    - secretKey: DECK_INTERNAL_KONG_ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_INTERNAL_KONG_ADMIN_PASSWORD
    - secretKey: DECK_KEYDB_HOST
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_KEYDB_HOST
    - secretKey: DECK_KONG_ADDR
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_KONG_ADDR
    - secretKey: DECK_KONG_LOGS_PLUGIN_ELASTIC_BASIC_AUTH
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_KONG_LOGS_PLUGIN_ELASTIC_BASIC_AUTH
    - secretKey: DECK_LEADERBOARD_AUTH
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_LEADERBOARD_AUTH
    - secretKey: DECK_LEADERBOARD_CORS_ORIGIN
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_LEADERBOARD_CORS_ORIGIN
    - secretKey: DECK_LEADERBOARD_DETAILS_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_LEADERBOARD_DETAILS_PASSWORD
    - secretKey: DECK_LEADERBOARD_HOST
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_LEADERBOARD_HOST
    - secretKey: DECK_LEADERBOARD_PORT
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_LEADERBOARD_PORT
    - secretKey: DECK_LEADERBOARD_PUBLIC_CONSUMER_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_LEADERBOARD_PUBLIC_CONSUMER_API_KEY
    - secretKey: DECK_LEADERBOARD_PUBLIC_CONSUMER_EMAIL
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_LEADERBOARD_PUBLIC_CONSUMER_EMAIL
    - secretKey: DECK_LEADERBOARD_SCHEME
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_LEADERBOARD_SCHEME
    - secretKey: DECK_NEXT_JS_BASIC_AUTH
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_NEXT_JS_BASIC_AUTH
    - secretKey: DECK_RED_TEAMING_HOST
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_RED_TEAMING_HOST
    - secretKey: DECK_RED_TEAMING_PORT
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_RED_TEAMING_PORT
    - secretKey: DECK_RED_TEAMING_SCHEME
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_RED_TEAMING_SCHEME
    - secretKey: DECK_RED_TEAMING_URL
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_RED_TEAMING_URL
    - secretKey: KONG_LOG_LEVEL
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_LOG_LEVEL
    - secretKey: KONG_PROXY_LISTEN
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PROXY_LISTEN
    - secretKey: DECK_VERCEL_PROTECTION_AUTH
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_VERCEL_PROTECTION_AUTH
    - secretKey: KONG_ADMIN_LISTEN
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_ADMIN_LISTEN
    - secretKey: KONG_DATABASE
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_DATABASE
    - secretKey: KONG_PG_DATABASE
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_DATABASE
    - secretKey: KONG_PG_HOST
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_HOST
    - secretKey: KONG_PG_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_PASSWORD
    - secretKey: KONG_PG_PORT
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_PORT
    - secretKey: KONG_PG_USER
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_USER
    - secretKey: KONG_PG_SSL
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_SSL
    - secretKey: KONG_PG_SSL_VERSION
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_SSL_VERSION
    - secretKey: KONG_PG_SSL_REQUIRED
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_SSL_REQUIRED
    - secretKey: KONG_PG_SSL_VERIFY
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_SSL_VERIFY
    - secretKey: KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE
    - secretKey: KONG_MEM_CACHE_SIZE
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_MEM_CACHE_SIZE
    - secretKey: KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS
    - secretKey: KONG_NGINX_HTTP_KEEPALIVE_REQUESTS
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_NGINX_HTTP_KEEPALIVE_REQUESTS
    - secretKey: KONG_PROXY_ACCESS_LOG
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PROXY_ACCESS_LOG
    - secretKey: KONG_SSL_PROTOCOLS
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_SSL_PROTOCOLS
    - secretKey: DECK_INITIAL_SAMPLE_MODEL_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_INITIAL_SAMPLE_MODEL_PASSWORD
    - secretKey: DECK_SAMPLE_MODEL_REAL_APIKEY
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: DECK_SAMPLE_MODEL_REAL_APIKEY
{{- end }}
