apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-migration-env-secret
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRefName }}
    kind: ClusterSecretStore
  target:
    name: gateway-migration-env-secret
  data:
    - secretKey: KONG_LOG_LEVEL
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_LOG_LEVEL
    - secretKey: KONG_PROXY_LISTEN
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PROXY_LISTEN
    - secretKey: KONG_DATABASE
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_DATABASE
    - secretKey: KONG_PG_DATABASE
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_DATABASE
    - secretKey: KONG_PG_HOST
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_HOST
    - secretKey: KONG_PG_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_PASSWORD
    - secretKey: KONG_PG_PORT
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_PORT
    - secretKey: KONG_PG_USER
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_USER
    - secretKey: KONG_PG_SSL
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_SSL
    - secretKey: KONG_PG_SSL_VERSION
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_SSL_VERSION
    - secretKey: KONG_PG_SSL_REQUIRED
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_SSL_REQUIRED
    - secretKey: KONG_PG_SSL_VERIFY
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PG_SSL_VERIFY
    - secretKey: KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE
    - secretKey: KONG_MEM_CACHE_SIZE
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_MEM_CACHE_SIZE
    - secretKey: KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS
    - secretKey: KONG_NGINX_HTTP_KEEPALIVE_REQUESTS
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_NGINX_HTTP_KEEPALIVE_REQUESTS
    - secretKey: KONG_PROXY_ACCESS_LOG
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_PROXY_ACCESS_LOG
    - secretKey: KONG_SSL_PROTOCOLS
      remoteRef:
        key: {{ .Values.externalSecret.repoName }}
        property: KONG_SSL_PROTOCOLS

