{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gateway-env-secret
  labels:
    {{- include "gateway-kong.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
