{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gateway-env-secret
  labels:
    {{- include "gateway-kong.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.gateway }}
  {{- if ne $key "enabled" }}
  {{ $key }}: {{ $val | default "" | toString | quote }}
  {{- end }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-migration-env-secret
  labels:
    {{- include "gateway-kong.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.gatewayMigration }}
  {{- if ne $key "enabled" }}
  {{ $key }}: {{ $val | default "" | toString | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-env-secret
  labels:
    {{- include "gateway-kong.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.elastic }}
  {{- if ne $key "enabled" }}
  {{ $key }}: {{ $val | default "" | toString | quote }}
  {{- end }}
  {{- end }}
{{- end }}
