{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: openfga-env-secret
  annotations:
    "helm.sh/hook-weight": "2"
    "helm.sh/hook": post-install, post-upgrade
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.openfga }}
  {{- if ne $key "enabled" }}
  {{ $key }}: {{ $val | default "" | toString | quote }}  {{- end }}
  {{- end }}
{{- end }}
