apiVersion: v2
name: enkryptai-lite
description: Enkryptai redteaming and guardrails
type: application
version: 1.0.6
appVersion: "1.0.6"
dependencies:
  
  - name: argo-workflow
    version: 1.0.0
    alias: argo-workflow
    repository: "file://./charts/argo-workflow"
    condition: argo-workflow.enabled

  - name: gpu-operator
    version: v24.9.0
    alias: gpu-operator
    repository: "https://helm.ngc.nvidia.com/nvidia"
    condition: gpu-operator.enabled

  - name: keydb
    version: 0.48.0
    alias: keydb
    repository: "https://enapter.github.io/charts/"
    condition: keydb.enabled

  - name: nats
    version: 1.3.14
    alias: nats
    repository: "https://nats-io.github.io/k8s/helm/charts"
    condition: nats.enabled

  - name: nack
    version: 0.29.2
    alias: nack
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nack.enabled

  - name: ingress-nginx
    version: 1.0.0
    alias: ingress-nginx
    repository: "file://./charts/ingress-nginx"
    condition: ingress-nginx.enabled

