apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-enkryptai-stack-test
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/enkryptai/helm-charts.git
    targetRevision: argocd-test
    path: argocd/enkryptai-stack
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: enkryptai-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
