replicaCount: 2

image:
  repository: 188451452903.dkr.ecr.us-east-1.amazonaws.com/enkryptai-dev/redteam-proxy
  pullPolicy: IfNotPresent
  tag: "dev"

nameOverride: ""
fullnameOverride: "redteam-proxy"

podAnnotations:
  reloader.stakater.com/auto: "true"

podLabels:
  app: redteam-proxy

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 50%

service:
  type: ClusterIP
  port: 9091
  targetPort: 9091
  name: http

env:
  - name: NATS_URL
    value: "nats://nats:4222"
  - name: IS_PROXY_MODE
    value: "true"
  - name: GR_MODELS_MODE
    value: "remote"
  - name: SENTRY_LITELLM_GATEWAY_API_KEY
    value: "sentry-litellm-gateway-secret-key"
  - name: SENTRY_LITELLM_GATEWAY_TIMEOUT
    value: "300"
  - name: SENTRY_LITELLM_GATEWAY_URL
    value: "http://enkryptai-litellm:4000"

resources:
  requests:
    cpu: 100m
    memory: 300Mi
  limits:
    cpu: 500m
    memory: 1Gi

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 9091
  initialDelaySeconds: 90
  timeoutSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 9091
  initialDelaySeconds: 30
  timeoutSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

externalSecret:
  enabled: true
  secretName: redteam-proxy-env-secret
  secretStoreRefName: enkryptai-clustersecret-store
  repoName: enkryptai/redteam-proxy

secrets:
  name: redteam-proxy-env-secret
  enabled: false
nodeSelector: {}

tolerations: []

affinity: {}
configMapNamespaces:
  - enkryptai-stack
  - redteam-jobs
configMap:
  # NEXT_PUBLIC_SUPABASE_URL: "https://auth.example.com/"
  ENDPOINT: http://supabase-storage.enkryptai-stack:5000/s3
  REDIS_URL: redis://keydb.enkryptai-stack:6379
  REGION: us-east-1
  SENTRY_LITELLM_GATEWAY_TIMEOUT: "300"
  SENTRY_LITELLM_GATEWAY_URL: http://enkryptai-litellm.enkryptai-stack:4000
  SIERRA_RELEASE: 59df177a7029c49f66ea01c0dddfbb5552b64f6d393ffe98a1ffa8bfaa0599d2
  SUPABASE_STORAGE_URL: http://supabase-storage.enkryptai-stack:5000/s3
  SUPABASE_URL: "https://auth.example.com"
